#cosito
print("       _                        ")
print("       \`*-.                   ")
print("        )  _`-.               ")
print("       .  : `. .                ")
print("       : _   '  \              ")
print("       ; *` _.   `*-._          ")
print("       `-.-'          `-.       ")
print("         ;       `       `.     ")
print("         :.       .        \    ")
print("         . \  .   :   .-'   .   ")
print("         '  `+.;  ;  '      :   ")
print("         :  '  |    ;       ;-. ")
print("         ; '   : :`-:     _.`* ;")
print(" ñau  .*' /  .*' ; .*`- +'  `*' ")
print("      `*-*   `*-*  `*-*'")